services:
  nextdeblog:
    build: ./nextdeblog
    image: nextdeblog
    container_name: nextdeblog
    ports:
      - "3000:3000"
    environment:
     - WATCHPACK_POLLING=true
    command: ash -c "npm run dev & npx prisma studio"
    volumes:
      - ./nextdeblog:/myapp
    restart: always
    tty: true
    stdin_open: true
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

volumes:
  postgres: