import type { Metadata } from 'next'
import './globals.css'
import NextAuthProvider from '@/app/providers/NextAuthProvider'
import AppProvider from './providers/provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <AppProvider>
            {children}
          </AppProvider>
        </NextAuthProvider>
      </body>
    </html>
  )
}
